<?php
    $data = '';
    $data = Mage::helper('instagrampro')->getConfigData();
    //	echo '<pre>';
    //	print_r($data); die;

?>
<link href='http://fonts.googleapis.com/css?family=Lato:300,400,700,400italic,300italic' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'EM_Instagrampro/css/owl.carousel.css'; ?>">
<link rel="stylesheet" href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'EM_Instagrampro/css/owl.theme.default.min.css'; ?>">
<script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'EM_Instagrampro/js/jquery-1.10.2.min.js';?>"></script>
<script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'EM_Instagrampro/js/owl.carousel.min.js'; ?>"></script>
<script>jQuery.noConflict();</script>
<h3><?php echo $data['title']; ?></h3>
<div class="owl-carousel">
    <?php  foreach ($data['images'] as $image) { ?>
        <div class="item">
            <img src="<?php echo $image['image']; ?>" alt="<?php echo $image['title']; ?>" class="img-responsive" />
        </div>
    <?php } ?>
</div>

<script>
    jQuery(document).ready(function() {
        var owl = jQuery('.owl-carousel');
        owl.owlCarousel({
            loop: true,
            items:<?php echo $data['item']; ?>,
            autoplay:true,
            autoplayTimeout:<?php echo $data['autoplayspeed']; ?>,
            nav:false,
            navText:['<','>'],
            margin:8,
            autoplayHoverPause:true,
            stagePadding:0,
            dots:false,
            rewindnav:false,
            responsiveClass: true,
            responsive: {
                0: {
                    items: 1
                },
                600: {
                    items: 3
                },
                1000: {
                    items: 5
                }
            }
        });
        owl.on('mousewheel', '.owl-stage', function (e) {
            if (e.deltaY>0) {
                owl.trigger('next.owl');
            } else {
                owl.trigger('prev.owl');
            }
            e.preventDefault();
        });
    });
</script>